### ISSUE TITLE
Nextcloud : redis read-only filesystem

### ISSUE THREAD

**Issue by darnold-zalf** [fairagro/basic_infrastructure#136]
Nextcloud was in a crashbackoffloop.  Attempting to restart nextcloud pod leads to the redis-readonly filesystem issue.

```
Configuring Redis as session handler
/entrypoint.sh: line 111: can't create /usr/local/etc/php/conf.d/redis-session.ini: Read-only file system
=> Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
```

I saw this on fizz yesterday.  Carsten said that he changed the behaviour of the pod to run as non-root.  I'm trying to locate where this change might be.  It is assumed to be in the new_draven branch : https://github.com/fairagro/basic_infrastructure/tree/new_draven

**Comment by darnold-zalf** [comment]
I'm not understanding why we would suddenly get this redis read-only issue.  Nothing should have changed on nextcloud in the 14 days or so since it was last synced.. Unless changes were done manually ?

I see the following in the NC pod (kubectl edit .. )  the smoking gun might be `runAsNonRoot: true`

```
...
   securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      readOnlyRootFilesystem: false
      runAsGroup: 82
      runAsNonRoot: true
      runAsUser: 82
```
