### ISSUE TITLE
onlyoffice-ee container is going OOM on Draven (production)

### ISSUE THREAD

**Issue by darnold-zalf** [fairagro/basic_infrastructure#90]
Since switching to the Enterprise edition of OnlyOffice (+ 100 user license) unfortunately we seem to have hit a resource limitation in the container.

I tried bumping the memory request to 1Gb but it doesn't seem to be taking : https://github.com/fairagro/basic_infrastructure/pull/88/commits/0e18c40d7b683e4ad91389301cf0db7742ec4153

Discussed briefly with Carsten 11.12.2025 - there shouldn't be any resource constraints in the k8s cluster, unless it's a default.  We seem to have plenty of spare capacity/resources in Draven.  This is only happening in Draven, not fizz.  So a bit more of a deep-dive will need to be done in January..

```
containerStatuses:
    - containerID: >-
        docker://4e2bc69e5cc9d421da9f32c15c3ff1266d599eeb299c487821b5b28380b32792
      image: 'sha256:1ebfd50a1dc8464747d16eea5b3735bc9f3cd6bfab586e63e4e96c2b1411b9fc'
      imageID: >-
        docker-pullable://onlyoffice/documentserver-ee@sha256:97475275c84857de7102058bde2acc0af8651e3cd0b137c766d5153ca193081e
      lastState:
        terminated:
          containerID: >-
            docker://3f15a10c6b8859d055ff50e41c364a748ca17f9a3443ecfb68747b85be3b9999
          exitCode: 0
          finishedAt: '2024-12-10T14:46:41Z'
          reason: OOMKilled
          startedAt: '2024-12-10T14:29:49Z'
```
